
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int BITWISE_NOT = 16;
  public static final int BITWISE_AND = 13;
  public static final int DIVIDE = 9;
  public static final int POWER = 11;
  public static final int GE = 27;
  public static final int XOR = 12;
  public static final int LPAREN = 29;
  public static final int SEMI = 28;
  public static final int BITWISE_OR = 14;
  public static final int FOR = 38;
  public static final int MINUS = 7;
  public static final int RPAREN = 32;
  public static final int NOT = 15;
  public static final int AND = 20;
  public static final int LT = 24;
  public static final int OR = 21;
  public static final int COMMA = 33;
  public static final int PLUS = 6;
  public static final int IF = 35;
  public static final int ASSIGN = 34;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int UNSIGNED_SHIFT_RIGHT = 19;
  public static final int error = 1;
  public static final int MODULO = 10;
  public static final int LCBRAC = 30;
  public static final int NUMBER = 2;
  public static final int IDENT = 5;
  public static final int EQ = 22;
  public static final int SHIFT_LEFT = 17;
  public static final int RCBRAC = 31;
  public static final int TIMES = 8;
  public static final int ELSE = 36;
  public static final int WHILE = 37;
  public static final int FLOAT = 3;
  public static final int NE = 23;
  public static final int STRING = 4;
  public static final int GT = 25;
  public static final int SHIFT_RIGHT = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "FLOAT",
  "STRING",
  "IDENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "POWER",
  "XOR",
  "BITWISE_AND",
  "BITWISE_OR",
  "NOT",
  "BITWISE_NOT",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "UNSIGNED_SHIFT_RIGHT",
  "AND",
  "OR",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "SEMI",
  "LPAREN",
  "LCBRAC",
  "RCBRAC",
  "RPAREN",
  "COMMA",
  "ASSIGN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR"
  };
}

