
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int BITWISE_NOT = 10;
  public static final int BITWISE_AND = 7;
  public static final int DIVIDE = 17;
  public static final int POWER = 19;
  public static final int GE = 26;
  public static final int UMINUS = 20;
  public static final int XOR = 6;
  public static final int LPAREN = 30;
  public static final int SEMI = 29;
  public static final int BITWISE_OR = 8;
  public static final int FOR = 39;
  public static final int MINUS = 15;
  public static final int RPAREN = 33;
  public static final int NOT = 9;
  public static final int AND = 27;
  public static final int LT = 23;
  public static final int OR = 28;
  public static final int COMMA = 34;
  public static final int PLUS = 14;
  public static final int IF = 36;
  public static final int ASSIGN = 35;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int UNSIGNED_SHIFT_RIGHT = 13;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int MODULO = 18;
  public static final int LCBRAC = 31;
  public static final int NUMBER = 2;
  public static final int IDENT = 5;
  public static final int EQ = 21;
  public static final int SHIFT_LEFT = 11;
  public static final int RCBRAC = 32;
  public static final int TIMES = 16;
  public static final int ELSE = 37;
  public static final int FUNC = 40;
  public static final int WHILE = 38;
  public static final int FLOAT = 3;
  public static final int NE = 22;
  public static final int STRING = 4;
  public static final int FALSE = 43;
  public static final int GT = 24;
  public static final int SHIFT_RIGHT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "FLOAT",
  "STRING",
  "IDENT",
  "XOR",
  "BITWISE_AND",
  "BITWISE_OR",
  "NOT",
  "BITWISE_NOT",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "UNSIGNED_SHIFT_RIGHT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "POWER",
  "UMINUS",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "SEMI",
  "LPAREN",
  "LCBRAC",
  "RCBRAC",
  "RPAREN",
  "COMMA",
  "ASSIGN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "FUNC",
  "RETURN",
  "TRUE",
  "FALSE"
  };
}

